export const IPC = {
  APP_GET_VERSION: 'app:get-version',
  APP_QUIT: 'app:quit',
  APP_SET_DIRTY: 'app:set-dirty',
  APP_REQUEST_CLOSE: 'app:request-close',
  APP_CLOSE_DECISION: 'app:close-decision',
  APP_TOGGLE_DEVTOOLS: 'app:toggle-devtools',
  APP_LOG_RENDERER_ERROR: 'app:log-renderer-error',
  APP_GET_ERROR_LOG_PATH: 'app:get-error-log-path',
  APP_SET_VERBOSE_LOGS: 'app:set-verbose-logs',
  APP_NEW_WINDOW: 'app:new-window',
  APP_GET_WINDOW_INIT: 'app:get-window-init',
  FILE_OPEN: 'file:open',
  FILE_OPEN_FOLDER: 'file:open-folder',
  FILE_SCAN_WORKSPACE: 'file:scan-workspace',
  FILE_READ: 'file:read',
  FILE_READ_BINARY: 'file:read-binary',
  FILE_SAVE: 'file:save',
  FILE_SAVE_AS: 'file:save-as',
  FILE_READ_IMAGE: 'file:read-image',
  FILE_SAVE_PASTED_IMAGE: 'file:save-pasted-image',
  FILE_EXPORT_HTML: 'file:export-html',
  FILE_EXPORT_PDF: 'file:export-pdf',
  FILE_UPDATE_TITLE: 'file:update-title',
  MARKS_LIST: 'marks:list',
  MARKS_CREATE: 'marks:create',
  MARKS_UPDATE: 'marks:update',
  MARKS_DELETE: 'marks:delete',
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
